/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProductsRouteImport } from './routes/المنتجات'
import { Route as FaqRouteImport } from './routes/الاسئلة'
import { Route as ContactRouteImport } from './routes/تواصل'
import { Route as CheckoutRouteImport } from './routes/الطلب'
import { Route as IndexRouteImport } from './routes/index'

const ProductsRoute = ProductsRouteImport.update({
  id: '/المنتجات',
  path: '/المنتجات',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/الاسئلة',
  path: '/الاسئلة',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/تواصل',
  path: '/تواصل',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/الطلب',
  path: '/الطلب',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/الطلب': typeof CheckoutRoute
  '/تواصل': typeof ContactRoute
  '/الاسئلة': typeof FaqRoute
  '/المنتجات': typeof ProductsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/الطلب': typeof CheckoutRoute
  '/تواصل': typeof ContactRoute
  '/الاسئلة': typeof FaqRoute
  '/المنتجات': typeof ProductsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/الطلب': typeof CheckoutRoute
  '/تواصل': typeof ContactRoute
  '/الاسئلة': typeof FaqRoute
  '/المنتجات': typeof ProductsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/الطلب' | '/تواصل' | '/الاسئلة' | '/المنتجات'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/الطلب' | '/تواصل' | '/الاسئلة' | '/المنتجات'
  id: '__root__' | '/' | '/الطلب' | '/تواصل' | '/الاسئلة' | '/المنتجات'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CheckoutRoute: typeof CheckoutRoute
  ContactRoute: typeof ContactRoute
  FaqRoute: typeof FaqRoute
  ProductsRoute: typeof ProductsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/المنتجات': {
      id: '/المنتجات'
      path: '/المنتجات'
      fullPath: '/المنتجات'
      preLoaderRoute: typeof ProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/الاسئلة': {
      id: '/الاسئلة'
      path: '/الاسئلة'
      fullPath: '/الاسئلة'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/تواصل': {
      id: '/تواصل'
      path: '/تواصل'
      fullPath: '/تواصل'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/الطلب': {
      id: '/الطلب'
      path: '/الطلب'
      fullPath: '/الطلب'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CheckoutRoute: CheckoutRoute,
  ContactRoute: ContactRoute,
  FaqRoute: FaqRoute,
  ProductsRoute: ProductsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
