/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as Char1578Char1608Char1575Char1589Char1604RouteImport } from './routes/تواصل'
import { Route as Char1575Char1604Char1605Char1606Char1578Char1580Char1575Char1578RouteImport } from './routes/المنتجات'
import { Route as Char1575Char1604Char1591Char1604Char1576RouteImport } from './routes/الطلب'
import { Route as Char1575Char1604Char1575Char1587Char1574Char1604Char1577RouteImport } from './routes/الاسئلة'
import { Route as IndexRouteImport } from './routes/index'

const Char1578Char1608Char1575Char1589Char1604Route =
  Char1578Char1608Char1575Char1589Char1604RouteImport.update({
    id: '/تواصل',
    path: '/تواصل',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char1575Char1604Char1605Char1606Char1578Char1580Char1575Char1578Route =
  Char1575Char1604Char1605Char1606Char1578Char1580Char1575Char1578RouteImport.update(
    {
      id: '/المنتجات',
      path: '/المنتجات',
      getParentRoute: () => rootRouteImport,
    } as any,
  )
const Char1575Char1604Char1591Char1604Char1576Route =
  Char1575Char1604Char1591Char1604Char1576RouteImport.update({
    id: '/الطلب',
    path: '/الطلب',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char1575Char1604Char1575Char1587Char1574Char1604Char1577Route =
  Char1575Char1604Char1575Char1587Char1574Char1604Char1577RouteImport.update({
    id: '/الاسئلة',
    path: '/الاسئلة',
    getParentRoute: () => rootRouteImport,
  } as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/الاسئلة': typeof Char1575Char1604Char1575Char1587Char1574Char1604Char1577Route
  '/الطلب': typeof Char1575Char1604Char1591Char1604Char1576Route
  '/المنتجات': typeof Char1575Char1604Char1605Char1606Char1578Char1580Char1575Char1578Route
  '/تواصل': typeof Char1578Char1608Char1575Char1589Char1604Route
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/الاسئلة': typeof Char1575Char1604Char1575Char1587Char1574Char1604Char1577Route
  '/الطلب': typeof Char1575Char1604Char1591Char1604Char1576Route
  '/المنتجات': typeof Char1575Char1604Char1605Char1606Char1578Char1580Char1575Char1578Route
  '/تواصل': typeof Char1578Char1608Char1575Char1589Char1604Route
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/الاسئلة': typeof Char1575Char1604Char1575Char1587Char1574Char1604Char1577Route
  '/الطلب': typeof Char1575Char1604Char1591Char1604Char1576Route
  '/المنتجات': typeof Char1575Char1604Char1605Char1606Char1578Char1580Char1575Char1578Route
  '/تواصل': typeof Char1578Char1608Char1575Char1589Char1604Route
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/الاسئلة' | '/الطلب' | '/المنتجات' | '/تواصل'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/الاسئلة' | '/الطلب' | '/المنتجات' | '/تواصل'
  id: '__root__' | '/' | '/الاسئلة' | '/الطلب' | '/المنتجات' | '/تواصل'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  Char1575Char1604Char1575Char1587Char1574Char1604Char1577Route: typeof Char1575Char1604Char1575Char1587Char1574Char1604Char1577Route
  Char1575Char1604Char1591Char1604Char1576Route: typeof Char1575Char1604Char1591Char1604Char1576Route
  Char1575Char1604Char1605Char1606Char1578Char1580Char1575Char1578Route: typeof Char1575Char1604Char1605Char1606Char1578Char1580Char1575Char1578Route
  Char1578Char1608Char1575Char1589Char1604Route: typeof Char1578Char1608Char1575Char1589Char1604Route
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/تواصل': {
      id: '/تواصل'
      path: '/تواصل'
      fullPath: '/تواصل'
      preLoaderRoute: typeof Char1578Char1608Char1575Char1589Char1604RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/المنتجات': {
      id: '/المنتجات'
      path: '/المنتجات'
      fullPath: '/المنتجات'
      preLoaderRoute: typeof Char1575Char1604Char1605Char1606Char1578Char1580Char1575Char1578RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/الطلب': {
      id: '/الطلب'
      path: '/الطلب'
      fullPath: '/الطلب'
      preLoaderRoute: typeof Char1575Char1604Char1591Char1604Char1576RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/الاسئلة': {
      id: '/الاسئلة'
      path: '/الاسئلة'
      fullPath: '/الاسئلة'
      preLoaderRoute: typeof Char1575Char1604Char1575Char1587Char1574Char1604Char1577RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  Char1575Char1604Char1575Char1587Char1574Char1604Char1577Route:
    Char1575Char1604Char1575Char1587Char1574Char1604Char1577Route,
  Char1575Char1604Char1591Char1604Char1576Route:
    Char1575Char1604Char1591Char1604Char1576Route,
  Char1575Char1604Char1605Char1606Char1578Char1580Char1575Char1578Route:
    Char1575Char1604Char1605Char1606Char1578Char1580Char1575Char1578Route,
  Char1578Char1608Char1575Char1589Char1604Route:
    Char1578Char1608Char1575Char1589Char1604Route,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
